/* Base de Datos del Nomenclador */
const baseDeDatos = [
    { nombre: "Alvear", desde: 2100, hasta: 2900, zona: "8", bajo: "COMISARIA 2DA RAMOS MEJIA", alto: "DESTACAMENTO LOMAS DEL MIRADOR" },
    { nombre: "José Nicolás de Arriola", desde: 1850, hasta: 2700, zona: "8", bajo: "NO EXISTE", alto: "DESTACAMENTO LOMAS DEL MIRADOR", observacion: "Límite con zona 11" },
    { nombre: "Av. de Mayo", desde: 1900, hasta: 2000, zona: "8", bajo: "COMISARIA 2DA RAMOS MEJIA", alto: "COMISARIA 1RA SAN JUSTO", limite: "par", observacion: "ESC. DON BOSCO - (PUERTAS ADENTRO LADO PAR DE CRIA. 8VA) CALLE Y VEREDAS CORRESPONDEN A COMISARIA RAMOS MEJIA/SAN JUSTO" },
    { nombre: "Albariños", desde: 2100, hasta: 2700, zona: "8", bajo: "COMISARIA 2DA RAMOS MEJIA", alto: "NO EXISTE" },
    { nombre: "Av. Gral. Enrique Mosconi", desde: 1100, hasta: 1550, zona: "11", bajo: "DEST. LOMAS DEL MIRADOR / CRIA. 9NA LOMAS DEL MILLON", alto: "COMISARIA 1RA SAN JUSTO", limite: "impar", observacion: "LADO PAR, MITAD DE CALLE MANO A GRAL PAZ CORRESPONDE A DESTACAMENTO LOMAS DEL MIRADOR" },
    { nombre: "Av. Gral. Enrique Mosconi", desde: 1550, hasta: 2200, zona: "8", bajo: "DEST. LOMAS DEL MIRADOR", alto: "COMISARIA 1RA SAN JUSTO", limite: "impar", observacion: "LADO PAR, MITAD DE CALLE MANO A GRAL PAZ CORRESPONDE A DESTACAMENTO LOMAS DEL MIRADOR" },
    { nombre: "Pedro Bonifacio Palacios", desde: 0, hasta: 500, zona: "9", bajo: "NO EXISTE", alto: "NO EXISTE", observacion: "Predio deportivo Ateneo" },
    { nombre: "Pedro Bonifacio Palacios", desde: 500, hasta: 1500, zona: "8", bajo: "NO EXISTE", alto: "NO EXISTE" },
    { nombre: "Av. Gral. San Martin", desde: 1200, hasta: 1500, zona: "9", bajo: "RAMOS MEJIA / LOMAS DEL MILLON", alto: "DEST. LOMAS DEL MIRADOR", limite: "impar", observacion: "LADO PAR, MITAD DE CALLE MANO A RAMOS CORRESPONDE A COMISARIA 9NA LOMAS DEL MILLON" },
    { nombre: "Av. Gral. San Martin", desde: 1500, hasta: 2800, zona: "8", bajo: "RAMOS MEJIA / LOMAS DEL MILLON", alto: "DEST. LOMAS DEL MIRADOR", limite: "impar", observacion: "LADO PAR, MITAD DE CALLE MANO A RAMOS CORRESPONDE A COMISARIA 9NA LOMAS DEL MILLON" },
    { nombre: "Avellaneda", desde: 2100, hasta: 2900, zona: "8", bajo: "COMISARIA 2DA RAMOS MEJIA", alto: "DESTACAMENTO LOMAS DEL MIRADOR" },
    { nombre: "Atuel", desde: 0, hasta: 300, zona: "8", bajo: "NO EXISTE", alto: "NO EXISTE" },
    { nombre: "Aconcagua", desde: 0, hasta: 200, zona: "8", bajo: "NO EXISTE", alto: "NO EXISTE", observacion: "Cría 8va Don Bosco" },
    { nombre: "Manuel Artigas", desde: 0, hasta: 500, zona: "11", bajo: "NO EXISTE", alto: "COMISARIA 1RA SAN JUSTO" },
    { nombre: "Manuel Artigas", desde: 500, hasta: 1200, zona: "8", bajo: "NO EXISTE", alto: "COMISARIA 1RA SAN JUSTO" },
    { nombre: "Felipe de Arana", desde: 500, hasta: 1100, zona: "8", bajo: "NO EXISTE", alto: "NO EXISTE" },
    { nombre: "Bolívar", desde: 1600, hasta: 1900, zona: "9", bajo: "COMISARIA 2DA RAMOS MEJIA", alto: "DEST. LOMAS DEL MIRADOR", observacion: "Ateneo" },
    { nombre: "Bolívar", desde: 1900, hasta: 2700, zona: "11", bajo: "COMISARIA 2DA RAMOS MEJIA", alto: "DEST. LOMAS DEL MIRADOR" },
    { nombre: "Cnel. Brandsen", desde: 1700, hasta: 2900, zona: "8", bajo: "COMISARIA 2DA RAMOS MEJIA", alto: "DEST. LOMAS DEL MIRADOR", limite: "par", observacion: "(PUERTAS ADENTRO LADO PAR DE CRIA. 8VA) CALLE Y VEREDAS CORRESPONDEN A COMISARIA 1RA SAN JUSTO" },
    { nombre: "Colombia", desde: 0, hasta: 600, zona: "11", bajo: "NO EXISTE", alto: "COMISARIA 1RA SAN JUSTO" },
    { nombre: "Colombia", desde: 600, hasta: 1200, zona: "8", bajo: "NO EXISTE", alto: "COMISARIA 1RA SAN JUSTO" },
    { nombre: "Cotagaita", desde: 2000, hasta: 2700, zona: "8", bajo: "COMISARIA 2DA RAMOS MEJIA", alto: "DEST. LOMAS DEL MIRADOR" },
    { nombre: "Virrey Cisneros", desde: 0, hasta: 600, zona: "9/11", bajo: "NO EXISTE", alto: "COMISARIA 1RA SAN JUSTO" },
    { nombre: "Virrey Cisneros", desde: 600, hasta: 800, zona: "NO EXISTE", bajo: "9/11", alto: "8/11",observacion: "NO EXISTE EL NUMERAL DESDE EL 601 AL 799" },
    { nombre: "Virrey Cisneros", desde: 800, hasta: 1100, zona: "8", bajo: "NO EXISTE", alto: "COMISARIA 1RA SAN JUSTO" },
    { nombre: "Caupolican", desde: 0, hasta: 100, zona: "9", bajo: "NO EXISTE", alto: "COMISARIA 1RA SAN JUSTO" },
    { nombre: "Caupolican", desde: 100, hasta: 300, zona: "9", bajo: "ZONA 9", alto: "ZONA 8", observacion: "NO EXISTE DESDE EL NUMERAL 101 AL 299" },
    { nombre: "Caupolican", desde: 300, hasta: 800, zona: "8", bajo: "NO EXISTE", alto: "COMISARIA 1RA SAN JUSTO" },
    { nombre: "Cerrito", desde: 1200, hasta: 1600, zona: "9", bajo: "COMISARIA 2DA RAMOS MEJIA", alto: "DEST. LOMAS DEL MIRADOR" },
    { nombre: "Cerrito", desde: 1600, hasta: 2800, zona: "11", bajo: "COMISARIA 2DA RAMOS MEJIA", alto: "DEST. LOMAS DEL MIRADOR" },
    { nombre: "Candelaria", desde: 0, hasta: 200, zona: "8", bajo: "NO EXISTE", alto: "NO EXISTE" },
    { nombre: "Valentín Cardoso", desde: 1300, hasta: 1600, zona: "9", bajo: "NO EXISTE", alto: "NO EXISTE" },
    { nombre: "Valentín Cardoso", desde: 1600, hasta: 2400, zona: "11", bajo: "NO EXISTE", alto: "NO EXISTE" },
    { nombre: "Dardo Rocha", desde: 0, hasta: 500, zona: "11", bajo: "NO EXISTE", alto: "DEST. LOMAS DEL MIRADOR" },
    { nombre: "Dardo Rocha", desde: 500, hasta: 700, zona: "8", bajo: "NO EXISTE", alto: "DEST. LOMAS DEL MIRADOR" },
    { nombre: "Formosa", desde: 1800, hasta: 2700, zona: "8", bajo: "NO EXISTE", alto: "DEST. LOMAS DEL MIRADOR" },
    { nombre: "Humboldt", desde: 0, hasta: 400, zona: "9", bajo: "NO EXISTE", alto: "COMISARIAS SAN JUSTO/RAMOS MEJIA", limite: "par", observacion: "ADVERTENCIA: Punto limítrofe no definido. Verifique con CRIA. 2DA RAMOS MEJIA antes de proceder. " },
    { nombre: "Humboldt", desde: 400, hasta: 1000, zona: "8", bajo: "NO EXISTE", alto: "COMISARIAS SAN JUSTO/RAMOS MEJIA", limite: "par", observacion: "ADVERTENCIA: Punto limítrofe no definido. Verifique con CRIA. 2DA RAMOS MEJIA antes de proceder. " },
    { nombre: "José Martí", desde: 2000, hasta: 2700, zona: "8", bajo: "NO EXISTE", alto: "DEST. LOMAS DEL MIRADOR" },
    { nombre: "Mármol", desde: 0, hasta: 500, zona: "11", bajo: "NO EXISTE", alto: "COMISARIA 1RA SAN JUSTO" },
    { nombre: "Mármol", desde: 500, hasta: 1200, zona: "8", bajo: "Zona 11", alto: "COMISARIA 1RA SAN JUSTO" },
    { nombre: "Malabia", desde: 0, hasta: 500, zona: "11", bajo: "NO EXISTE", alto: "NO EXISTE" },
    { nombre: "Malabia", desde: 500, hasta: 900, zona: "8", bajo: "NO EXISTE", alto: "NO EXISTE" },
    { nombre: "Mariano Moreno", desde: 1600, hasta: 1900, zona: "9", bajo: "COMISARIA 2DA RAMOS MEJIA", alto: "DEST. LOMAS DEL MIRADOR" },
    { nombre: "Mariano Moreno", desde: 1900, hasta: 2800, zona: "11", bajo: "COMISARIA 2DA RAMOS MEJIA", alto: "DEST. LOMAS DEL MIRADOR" },
    { nombre: "Necochea", desde: 2000, hasta: 2700, zona: "8", bajo: "NO EXISTE", alto: "DEST. LOMAS DEL MIRADOR" },
    { nombre: "Olaya", desde: 1900, hasta: 2600, zona: "8", bajo: "NO EXISTE", alto: "DEST. LOMAS DEL MIRADOR" },
    { nombre: "Domingo Olivera", desde: 600, hasta: 900, zona: "8", bajo: "NO EXISTE", alto: "NO EXISTE" },
    { nombre: "J. L. Pereyra", desde: 0, hasta: 600, zona: "9", bajo: "NO EXISTE", alto: "NO EXISTE" },
    { nombre: "J. L. Pereyra", desde: 600, hasta: 1200, zona: "8", bajo: "NO EXISTE", alto: "NO EXISTE" },
    { nombre: "Pringles", desde: 1700, hasta: 2700, zona: "8", bajo: "COMISARIA 2DA RAMOS MEJIA", alto: "DEST. LOMAS DEL MIRADOR" },
    { nombre: "Pirovano", desde: 300, hasta: 800, zona: "8", bajo: "NO EXISTE", alto: "NO EXISTE" },
    { nombre: "Coronel Pizarro", desde: 00, hasta: 500, zona: "9", bajo: "NO EXISTE", alto: "NO EXISTE" },
    { nombre: "Coronel Pizarro", desde: 500, hasta: 700, zona: "8", bajo: "NO EXISTE", alto: "NO EXISTE" },
    { nombre: "Páez", desde: 800, hasta: 1200, zona: "8", bajo: "NO EXISTE", alto: "COMISARIA 1RA SAN JUSTO" },
    { nombre: "Pepirí", desde: 0, hasta: 200, zona: "8", bajo: "NO EXISTE", alto: "NO EXISTE" },
    { nombre: "Salta", desde: 0, hasta: 500, zona: "11", bajo: "NO EXISTE", alto: "COMISARIA 1RA SAN JUSTO" },
    { nombre: "Salta", desde: 500, hasta: 800, zona: "8", bajo: "COMISARIA 1RA SAN JUSTO", alto: "COMISARIA 1RA SAN JUSTO" },
    { nombre: "Temple", desde: 1700, hasta: 1900, zona: "9", bajo: "NO EXISTE", alto: "DEST. LOMAS DEL MIRADOR" },
    { nombre: "Temple", desde: 1900, hasta: 2800, zona: "11", bajo: "NO EXISTE", alto: "DEST. LOMAS DEL MIRADOR" },
    { nombre: "Florencio Varela", desde: 0, hasta: 400, zona: "11", bajo: "NO EXISTE", alto: "COMISARIA 1RA SAN JUSTO" },
    { nombre: "Florencio Varela", desde: 400, hasta: 1200, zona: "8", bajo: "NO EXISTE", alto: "COMISARIA 1RA SAN JUSTO" },
    { nombre: "Venezuela", desde: 300, hasta: 800, zona: "8", bajo: "COMISARIA 1RA SAN JUSTO", alto: "COMISARIA 1RA SAN JUSTO" },
    { nombre: "Tomás Justo Villegas", desde: 0, hasta: 400, zona: "11", bajo: "NO EXISTE", alto: "COMISARIA 1RA SAN JUSTO" },
    { nombre: "Tomás Justo Villegas", desde: 400, hasta: 1100, zona: "8", bajo: "NO EXISTE", alto: "COMISARIA 1RA SAN JUSTO" }
];
